<?php

return [
    'filtro-cartucho-industrial' => [
        'category' => 'filtracion',
        'name' => 'Filtro de Cartucho Industrial',
        'image' => 'img/muestra.jpg',
        'spec' => 'Microfiltracion de precision | Capacidad: 500-5000 m3/h',
        'summary' => 'Filtros de cartucho para sistemas cerrados con alta eficiencia de retencion.',
        'description' => 'Solucion de microfiltracion para capturar solidos finos en lineas de proceso. Recomendado para sectores alimentario, quimico y tratamiento de aguas de proceso.',
        'features' => [
            'Material: Poliester termofusionado',
            'Presion maxima: 10 bar',
            'Temperatura: -10C a 80C',
            'Vida util: 2000-3000 horas',
        ],
        'applications' => [
            'Prefiltracion de agua de proceso',
            'Proteccion de equipos aguas abajo',
            'Filtracion de fluidos industriales',
        ],
    ],
    'filtracion-por-bolsa' => [
        'category' => 'filtracion',
        'name' => 'Sistema de Filtracion por Bolsa',
        'image' => 'img/muestra.jpg',
        'spec' => 'Filtracion de gases | Caudal: 1000-10000 m3/h',
        'summary' => 'Sistema modular de bolsas reemplazables para despolvorizacion industrial.',
        'description' => 'Equipo de filtracion robusto para captura de polvo en instalaciones industriales. Facil acceso para mantenimiento y alta continuidad de operacion.',
        'features' => [
            'Material filtrante: Fieltro acrilico',
            'Presion diferencial: 0.5-2.5 mbar',
            'Eficiencia: 99.8%',
            'Limpieza: Sistema de pulso inverso',
        ],
        'applications' => [
            'Aspiracion de polvo de proceso',
            'Filtracion de aire en lineas de produccion',
            'Control de emisiones en planta',
        ],
    ],
    'filtro-mallas-metalicas' => [
        'category' => 'filtracion',
        'name' => 'Filtro de Mallas Metalicas',
        'image' => 'img/muestra.jpg',
        'spec' => 'Retencion de particulas gruesas | Malla: 10-500 um',
        'summary' => 'Filtro de acero inoxidable para prefiltracion y proteccion de equipos.',
        'description' => 'Elemento de filtracion mecanica con diferentes grados de malla para separar solidos de mayor tamano en fluidos de proceso.',
        'features' => [
            'Material: Acero inoxidable 316L',
            'Presion maxima: 25 bar',
            'Rango de malla: 10-500 um',
            'Mantenimiento: Facil desmontaje',
        ],
        'applications' => [
            'Proteccion de bombas y valvulas',
            'Prefiltracion de lineas de produccion',
            'Retencion de particulado en liquidos',
        ],
    ],
    'filtro-carbon-activado' => [
        'category' => 'filtracion',
        'name' => 'Filtro de Carbon Activado',
        'image' => 'img/muestra.jpg',
        'spec' => 'Adsorcion y desodorizacion | Purificacion avanzada',
        'summary' => 'Sistema de adsorcion para reducir compuestos organicos y olores.',
        'description' => 'Equipo para mejorar la calidad de fluidos mediante adsorcion en carbon granular, con configuraciones para distintos tiempos de contacto.',
        'features' => [
            'Carbon: Grado industrial ASTM',
            'Capacidad de adsorcion: 50-200 g/l',
            'Tiempo de contacto: 5-15 minutos',
            'Regimen: Ascendente o descendente',
        ],
        'applications' => [
            'Pulido final de agua de proceso',
            'Eliminacion de olores en corrientes de aire',
            'Reduccion de compuestos organicos',
        ],
    ],
    'filtro-membrana-ultrafiltracion' => [
        'category' => 'filtracion',
        'name' => 'Filtro de Membrana (Ultrafiltracion)',
        'image' => 'img/muestra.jpg',
        'spec' => 'Microfiltracion avanzada | Poro: 0.1-0.5 um',
        'summary' => 'Tecnologia de membrana para retencion de microparticulas y coloides.',
        'description' => 'Sistema de ultrafiltracion de alta precision orientado a procesos que requieren estabilidad de calidad en salida y reduccion de carga microbiologica.',
        'features' => [
            'Tipo de membrana: Polisulfona',
            'MWCO: 5,000-100,000 Da',
            'Flujo: 50-500 l/m2/h',
            'Retencion: 99.99%',
        ],
        'applications' => [
            'Tratamiento de agua industrial',
            'Recuperacion de producto',
            'Clarificacion de corrientes liquidas',
        ],
    ],
    'filtro-ceramica-porosa' => [
        'category' => 'filtracion',
        'name' => 'Filtro de Ceramica Porosa',
        'image' => 'img/muestra.jpg',
        'spec' => 'Filtracion de precision | Aplicaciones criticas',
        'summary' => 'Velas ceramicas para separaciones finas en condiciones exigentes.',
        'description' => 'Elemento filtrante para aplicaciones de alta exigencia termica y quimica, con estabilidad dimensional y excelente repetibilidad de filtrado.',
        'features' => [
            'Material: Ceramica Al2O3',
            'Tamano de poro: 0.2-10 um',
            'Temperatura maxima: 250C',
            'Presion maxima: 5 bar',
        ],
        'applications' => [
            'Procesos quimicos especiales',
            'Filtracion en farmaceutica',
            'Filtracion de bebidas y liquidos tecnicos',
        ],
    ],
    'separador-centrifugo-industrial' => [
        'category' => 'separacion',
        'name' => 'Separador Centrifugo Industrial',
        'image' => 'img/muestra.jpg',
        'spec' => 'Separacion por fuerza centrifuga | Caudal: 100-5000 l/h',
        'summary' => 'Separacion rapida de solidos en suspension mediante alta rotacion.',
        'description' => 'Equipo para procesos en continuo con alta capacidad de separacion y tiempos de respuesta cortos en aplicaciones de clarificacion.',
        'features' => [
            'RPM maximo: 3600',
            'Fuerza centrifuga: 200-3000 G',
            'Material: Acero inoxidable 316L',
            'Eficiencia: 99.5%',
        ],
        'applications' => [
            'Separacion solido-liquido en linea',
            'Clarificacion de corrientes de proceso',
            'Reduccion de carga de particulas',
        ],
    ],
    'separador-magnetico' => [
        'category' => 'separacion',
        'name' => 'Separador Magnetico',
        'image' => 'img/muestra.jpg',
        'spec' => 'Separacion ferromagnetica | Intensidad: 1000-8000 Gauss',
        'summary' => 'Extraccion de particulas ferromagneticas de fluidos y gases.',
        'description' => 'Sistema magnetico de alta intensidad para proteger maquinaria y mejorar la calidad del producto al retirar particulas metalicas.',
        'features' => [
            'Imanes de neodimio de alto rendimiento',
            'Rendimiento de captura: 99.9%',
            'Temperatura operativa: -20C a 60C',
            'Mantenimiento: Bajo requerimiento',
        ],
        'applications' => [
            'Proteccion de equipos rotativos',
            'Separacion de contaminacion metalica',
            'Lineas de proceso alimentario e industrial',
        ],
    ],
    'decantador-estatico' => [
        'category' => 'separacion',
        'name' => 'Decantador Estatico',
        'image' => 'img/muestra.jpg',
        'spec' => 'Sedimentacion por gravedad | Volumen: 100-10000 l',
        'summary' => 'Separacion por sedimentacion para corrientes con solidos densos.',
        'description' => 'Solucion de separacion por tiempo de residencia para aplicaciones donde se requiere sencillez operativa y bajo consumo energetico.',
        'features' => [
            'Tiempo de sedimentacion: 2-8 horas',
            'Eficiencia: 85-95%',
            'Estructura: Acero con recubrimiento epoxico',
            'Purga: Manual o automatica',
        ],
        'applications' => [
            'Tratamiento de aguas de proceso',
            'Separacion primaria de solidos',
            'Acumulacion y purga de lodos',
        ],
    ],
    'clarificador-placas-paralelas' => [
        'category' => 'separacion',
        'name' => 'Clarificador de Placas Paralelas',
        'image' => 'img/muestra.jpg',
        'spec' => 'Sedimentacion acelerada | Caudal: 500-50000 l/h',
        'summary' => 'Separacion compacta con placas inclinadas para alto rendimiento.',
        'description' => 'Equipo para mejorar la velocidad de sedimentacion y reducir superficie instalada en plantas de tratamiento y procesos industriales.',
        'features' => [
            'Angulo de placas: 45-60 grados',
            'Espaciado entre placas: 50-100 mm',
            'Eficiencia: 90-98%',
            'Tiempo de residencia: 30-60 min',
        ],
        'applications' => [
            'Clarificacion de agua industrial',
            'Separacion de solidos en suspension',
            'Tratamiento fisico-quimico',
        ],
    ],
    'separador-ciclon' => [
        'category' => 'separacion',
        'name' => 'Separador de Ciclon',
        'image' => 'img/muestra.jpg',
        'spec' => 'Separacion por flujo rotacional | Tamano: 100-1000 mm',
        'summary' => 'Separacion de particulas en gases con baja complejidad operativa.',
        'description' => 'Solucion mecanica para captura de particulas en corrientes gaseosas con bajo costo operativo y mantenimiento reducido.',
        'features' => [
            'Caida de presion: 50-250 Pa',
            'Eficiencia: 80-95%',
            'Tamano minimo separable: 5-10 um',
            'Instalacion: Horizontal o vertical',
        ],
        'applications' => [
            'Pre-separacion de polvo en gases',
            'Proteccion de filtros finales',
            'Sistemas de aspiracion industrial',
        ],
    ],
    'espesador-gravedad' => [
        'category' => 'separacion',
        'name' => 'Espesador de Gravedad',
        'image' => 'img/muestra.jpg',
        'spec' => 'Concentracion de lodos | Diametro: 2-50 m',
        'summary' => 'Equipo para aumentar concentracion de solidos en suspension.',
        'description' => 'Sistema de espesamiento para reduccion de volumen de lodo y optimizacion de las etapas posteriores de deshidratacion.',
        'features' => [
            'Mecanismo: Rastrillos de fondo lento',
            'Concentracion de salida: 15-30% ST',
            'Tiempo de residencia: 8-24 horas',
            'Control: Automatizacion con PLC',
        ],
        'applications' => [
            'Tratamiento de efluentes',
            'Concentracion previa a deshidratacion',
            'Gestion de lodos industriales',
        ],
    ],
];
